[package]
name = "musicos"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
bps = { git = "https://github.com/unconfirmedlabs/bps.git", rev = "4ca1972a67d35c972ca567de7b08315e3778e52b" }
share = { git = "https://github.com/misofm/share.git", rev = "e635fa7a85fdfb433e105e9e0460263fdbec54ad" }
